spring.application.name=KnjiznicaSpring

spring.datasource.url=jdbc:mysql://localhost:3306/knjiznica_db
spring.datasource.username=knjiznica_user
spring.datasource.password=knjiznica_user

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
