spring.application.name=KnjiznicaSpring

# Thymeleaf - turn off caching for development
spring.thymeleaf.cache=false

# MySQL database
spring.datasource.url=jdbc:mysql://localhost:3306/knjiznica_db
spring.datasource.username=knjiznica_user
spring.datasource.password=knjiznica_user

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true